import type { AnnotationKind, ReadingAnnotation } from '../types';

export const ANNOTATION_EXPORT_FOLDER = 'Obsidian Books/Exports';

export interface ExportableAnnotation extends ReadingAnnotation {
	bookKey: string;
	bookTitle: string;
}

function pluralKind(kind: AnnotationKind): 'highlights' | 'quotes' {
	return kind === 'highlight' ? 'highlights' : 'quotes';
}

function displayKind(kind: AnnotationKind): 'Highlights' | 'Quotes' {
	return kind === 'highlight' ? 'Highlights' : 'Quotes';
}

function normalizedHeading(value: string): string {
	return value.replace(/\r?\n/g, ' ').replace(/\s+/g, ' ').trim() || 'Untitled';
}

function quoteLines(text: string): string {
	return text
		.trim()
		.split(/\r?\n/)
		.map((line) => `> ${line}`)
		.join('\n');
}

function sourceLink(annotation: ReadingAnnotation): string {
	const source = annotation.sourcePath.replace(/\.md$/i, '');
	return `[[${source}|${normalizedHeading(annotation.chapterTitle)}]]`;
}

function reopenLink(annotation: ReadingAnnotation, vaultName: string): string {
	const params = new URLSearchParams({
		vault: vaultName,
		id: annotation.id,
	});
	return `obsidian://books-open?${params.toString()}`;
}

function compareAnnotations(left: ExportableAnnotation, right: ExportableAnnotation): number {
	return (
		left.bookTitle.localeCompare(right.bookTitle, undefined, { sensitivity: 'base' }) ||
		left.bookKey.localeCompare(right.bookKey) ||
		left.sourcePath.localeCompare(right.sourcePath, undefined, { sensitivity: 'base' }) ||
		left.fraction - right.fraction ||
		left.createdAt.localeCompare(right.createdAt) ||
		left.id.localeCompare(right.id)
	);
}

function formatEntry(annotation: ExportableAnnotation, vaultName: string): string {
	const heading = annotation.heading
		? `\n- Heading: ${normalizedHeading(annotation.heading)}`
		: '';
	const destination = annotation.destinationPath
		? `\n- Saved quote: [[${annotation.destinationPath.replace(/\.md$/i, '')}]]`
		: '';
	return [
		quoteLines(annotation.selectedText),
		'',
		`- Source: ${sourceLink(annotation)}${heading}`,
		`- Captured: ${annotation.createdAt}`,
		`- Location: ${Math.round(annotation.fraction * 100)}%${destination}`,
		`- [Open in Obsidian Books](${reopenLink(annotation, vaultName)})`,
		'',
		`^${annotation.id}`,
	].join('\n');
}

export function annotationExportMarker(kind: AnnotationKind): string {
	return `<!-- obsidian-books-managed-export: ${pluralKind(kind)} -->`;
}

export function annotationExportPath(kind: AnnotationKind): string {
	return `${ANNOTATION_EXPORT_FOLDER}/All ${displayKind(kind)}.md`;
}

export function timestampedAnnotationExportPath(
	kind: AnnotationKind,
	generatedAt: string,
	suffix = 0,
): string {
	const timestamp = generatedAt
		.replace(/\.\d{3}Z$/, 'Z')
		.replace(/[:T]/g, '-')
		.replace(/Z$/, '');
	const collisionSuffix = suffix > 0 ? ` ${suffix + 1}` : '';
	return `${ANNOTATION_EXPORT_FOLDER}/All ${displayKind(kind)} ${timestamp}${collisionSuffix}.md`;
}

export function isManagedAnnotationExport(content: string, kind: AnnotationKind): boolean {
	return content.includes(annotationExportMarker(kind));
}

export function formatAnnotationExport(
	kind: AnnotationKind,
	annotations: readonly ExportableAnnotation[],
	vaultName: string,
	generatedAt: string,
): string {
	const matching = annotations.filter((annotation) => annotation.kind === kind);
	const sorted = [...matching].sort(compareAnnotations);
	const bookCount = new Set(sorted.map((annotation) => annotation.bookKey)).size;
	const kindLabel = sorted.length === 1 ? kind : pluralKind(kind);
	const lines = [
		`# All ${displayKind(kind)}`,
		'',
		annotationExportMarker(kind),
		'',
		'> [!NOTE]',
		`> Generated by Obsidian Books on ${generatedAt}.`,
		`> ${sorted.length} ${kindLabel} from ${bookCount} ${bookCount === 1 ? 'book' : 'books'}.`,
		'> Run the matching Obsidian Books export command to refresh this managed note.',
	];

	let previousBookKey: string | undefined;
	let previousSourcePath: string | undefined;
	for (const annotation of sorted) {
		if (annotation.bookKey !== previousBookKey) {
			lines.push('', `## ${normalizedHeading(annotation.bookTitle)}`);
			previousBookKey = annotation.bookKey;
			previousSourcePath = undefined;
		}
		if (annotation.sourcePath !== previousSourcePath) {
			lines.push('', `### ${normalizedHeading(annotation.chapterTitle)}`);
			previousSourcePath = annotation.sourcePath;
		}
		lines.push('', formatEntry(annotation, vaultName));
	}

	return `${lines.join('\n')}\n`;
}
